# Generated by Django 4.0.4 on 2022-05-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_store', '0003_alter_productallergen_allergen_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productallergen',
            name='generic_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='wedish_store.genericproduct', verbose_name='generic product'),
        ),
    ]
