# Generated by Django 4.0.4 on 2022-04-25 18:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wedish_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('category', models.PositiveIntegerField(choices=[(0, 'dish'), (1, 'drink'), (2, 'service')], default=0, verbose_name='Status')),
                ('recommended_retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='recommended retail price')),
                ('picture', models.ImageField(default='wedish_recipy/img/default.jpg', upload_to='', verbose_name='picture')),
                ('description', tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodIngradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantity')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='wedish_recipy.good', verbose_name='good')),
                ('ingradient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='wedish_store.product', verbose_name='ingredient')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='wedish_store.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'good ingredient',
                'verbose_name_plural': 'good ingredients',
            },
        ),
    ]
