# Generated by Django 4.0.4 on 2022-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_recipy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'dish'), (1, 'drink'), (2, 'service')], default=0, verbose_name='status'),
        ),
    ]
