# Generated by Django 4.0.4 on 2022-04-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_recipy', '0002_good_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodIngradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='wedish_recipy.good', verbose_name='good')),
            ],
            options={
                'verbose_name': 'good ingredient',
                'verbose_name_plural': 'good ingredients',
            },
        ),
    ]
