# Generated by Django 4.0.4 on 2022-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_recipy', '0002_alter_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodingradient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='quantity'),
        ),
    ]
