# Generated by Django 4.0.4 on 2022-04-26 15:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('accepts_for_production', models.BooleanField(default=False, verbose_name='Accepts for production')),
                ('description', tinymce.models.HTMLField(help_text='Short description of this space', max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Space Category')),
                ('description', tinymce.models.HTMLField(help_text='Short description of this space category', max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_identifier', models.PositiveIntegerField(default=0, verbose_name='Public identifier')),
                ('seats_number', models.PositiveIntegerField(default=1, verbose_name='Seats number')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='wedish_pub.space', verbose_name='Space')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='space_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='wedish_pub.spacecategory', verbose_name='Space'),
        ),
    ]
