# Generated by Django 4.0.4 on 2022-04-27 18:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_pub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'space', 'verbose_name_plural': 'spaces'},
        ),
        migrations.AlterModelOptions(
            name='spacecategory',
            options={'verbose_name': 'space category', 'verbose_name_plural': 'space categories'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'table', 'verbose_name_plural': 'tables'},
        ),
        migrations.AlterField(
            model_name='space',
            name='accepts_for_production',
            field=models.BooleanField(default=False, verbose_name='accepts for production'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=tinymce.models.HTMLField(help_text='Short description of this space', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='wedish_pub.spacecategory', verbose_name='space'),
        ),
        migrations.AlterField(
            model_name='spacecategory',
            name='description',
            field=tinymce.models.HTMLField(help_text='Short description of this space category', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='spacecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='space category'),
        ),
        migrations.AlterField(
            model_name='table',
            name='public_identifier',
            field=models.PositiveIntegerField(default=0, verbose_name='public identifier'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats_number',
            field=models.PositiveIntegerField(default=1, verbose_name='seats number'),
        ),
        migrations.AlterField(
            model_name='table',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='wedish_pub.space', verbose_name='space'),
        ),
    ]
