# Generated by Django 4.0.4 on 2022-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_pub', '0002_alter_space_options_alter_spacecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
