# Generated by Django 4.0.4 on 2022-04-20 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='ex.: Salad, Roast, Pizza...', max_length=30, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex.: Day menu, Festive menu, Ordinary menu', max_length=30, verbose_name='Name')),
                ('valid_from', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Valid from')),
                ('valid_untill', models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid untill')),
                ('publicity', models.PositiveIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=1, verbose_name='Publicity')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['name', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ManuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('category_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedish_menu.category', verbose_name='Catyegory group')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedish_menu.menu', verbose_name='Menu'),
        ),
    ]
