# Generated by Django 4.0.4 on 2022-04-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
    ]
