# Generated by Django 4.0.4 on 2022-04-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuitem',
            name='category_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedish_menu.category', verbose_name='Category group'),
        ),
    ]
