# Generated by Django 4.0.4 on 2022-04-20 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='valid_from',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='valid_untill',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Valid untill'),
        ),
    ]
