# Generated by Django 4.0.4 on 2022-04-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0002_alter_category_options_alter_menuitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='priority_index',
        ),
    ]
