# Generated by Django 4.0.4 on 2022-04-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0003_remove_category_priority_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=63, verbose_name='short_description')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedish_menu.menuitem', verbose_name='menu_item')),
            ],
        ),
    ]
