# Generated by Django 4.0.4 on 2022-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0004_menuitemline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItemLine',
        ),
    ]
