# Generated by Django 4.0.4 on 2022-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_menu', '0005_delete_menuitemline'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='net price'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='vat amount'),
        ),
    ]
