# Generated by Django 4.0.4 on 2022-04-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Customer')),
                ('total_price', models.IntegerField(db_index=True, verbose_name='Total price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(db_index=True, max_length=100, verbose_name='Quantity')),
                ('price', models.CharField(db_index=True, max_length=100, verbose_name='Price')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='completed_at')),
                ('table_number', models.CharField(db_index=True, max_length=100, verbose_name='Table number')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(db_index=True, max_length=100, verbose_name='Payment method')),
                ('currency', models.CharField(db_index=True, max_length=10, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Rate')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
            ],
        ),
    ]
