# Generated by Django 4.0.4 on 2022-04-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vat',
            old_name='rate',
            new_name='unit_rate',
        ),
    ]
