# Generated by Django 4.0.4 on 2022-04-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_pub', '0001_initial'),
        ('wedish_menu', '0002_alter_category_options_alter_menuitem_options'),
        ('wedish_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['table', 'server', 'estimated_to_complete'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tables', to='wedish_pub.table', verbose_name='table'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='wedish_accounting.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='wedish_menu.menuitem', verbose_name='menu item'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='wedish_accounting.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Rate'),
        ),
    ]
