# Generated by Django 4.0.4 on 2022-05-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_accounting', '0002_order_total_price_squashed_0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='region',
        ),
        migrations.RemoveField(
            model_name='vat',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SubRegion',
        ),
        migrations.DeleteModel(
            name='VAT',
        ),
    ]
