# Generated by Django 4.0.4 on 2022-05-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_accounting', '0004_companyname_squashed_0005_rename_companyname_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='wedish_accounting.order', verbose_name='order'),
        ),
    ]
