# Generated by Django 4.0.4 on 2022-05-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_accounting', '0004_companyname_squashed_0005_rename_companyname_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='BIC',
            new_name='bic',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='IBAN',
            new_name='iban',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='VAT_id',
            new_name='vat_id',
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='wedish_accounting.company', verbose_name='company'),
        ),
    ]
