# Generated by Django 4.0.4 on 2022-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedish_accounting', '0005_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
    ]
